// src/vue/SocialShareBox.vue
<template>
	<div class="ss-box" :style="boxStyle">
		<SocialShareButton
			v-for="key in resolvedNetworks"
			:key="key"
			:network="key"
			:link="link"
			:text="text"
			:subject="subject"
			:showLabel="showLabel"
			:customStyle="buttonStyle"
		/>
	</div>
</template>

<script lang="ts">
import { defineComponent, computed, PropType, CSSProperties } from "vue";
import SocialShareButton from "./SocialShareButton.vue";
import { getSupportedNetworks } from "../core/index";
import type { NetworkKey } from "../core/types";

export default defineComponent({
	name: "SocialShareBox",
	components: { SocialShareButton },
	props: {
		link: { type: String, required: true },
		socials: { type: Array as PropType<NetworkKey[]>, default: null },
		text: { type: String, default: "" },
		subject: { type: String, default: "" },
		showLabel: { type: Boolean, default: true },
		direction: { type: String as PropType<"row" | "column">, default: "row" },
		gap: { type: String, default: "8px" },
		buttonStyle: { type: Object as PropType<CSSProperties>, default: () => ({}) },
	},
	setup(props) {
		const resolvedNetworks = computed<NetworkKey[]>(
			() => props.socials ?? getSupportedNetworks().map((n) => n.key),
		);

		const boxStyle = computed<CSSProperties>(() => ({
			display: "flex",
			flexDirection: props.direction,
			flexWrap: "wrap",
			gap: props.gap,
		}));

		return { resolvedNetworks, boxStyle };
	},
});
</script>

// src/react/SocialShareBox.tsx
import React, { CSSProperties } from "react";
import { SocialShareButton } from "./SocialShareButton";
import { getSupportedNetworks } from "../core/index";
import type { SocialShareBoxProps } from "../core/types";

interface Props extends SocialShareBoxProps {
	buttonStyle?: CSSProperties;
	className?: string;
	style?: CSSProperties;
}

export function SocialShareBox({
	link,
	socials = undefined,
	text = "",
	subject = "",
	showLabel = true,
	direction = "row",
	gap = "8px",
	buttonStyle = {},
	className = "",
	style = {},
}: Props) {
	const allKeys = getSupportedNetworks().map((n) => n.key);
	const keys = socials ?? allKeys;

	return (
		<div
			className={`ss-box ${className}`.trim()}
			style={{
				display: "flex",
				flexDirection: direction,
				flexWrap: "wrap",
				gap,
				...style,
			}}
		>
			{keys.map((key) => (
				<SocialShareButton
					key={key}
					network={key}
					link={link}
					text={text}
					subject={subject}
					showLabel={showLabel}
					style={buttonStyle}
				/>
			))}
		</div>
	);
}
